### STAGE 1: Build ###
# FROM node:18.4.0-alpine AS build
FROM node:24-bullseye AS build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
#RUN npm install @angular/animations
#ENV PATH="./node_modules/.bin:$PATH"
COPY . .
# RUN npm run build --aot
RUN npm run ng build --configuration=production

### STAGE 2: Run ###
FROM nginx:1.25.2-alpine-slim
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/template/browser /usr/share/nginx/html
EXPOSE 80
