events {}
http {
  server {
    listen 80;
    server_name eligibility-admin.univers.ci;

    root /usr/share/nginx/html;
    index index.html;

    # Ensures that all non-existent file requests are redirected to index.html for Angular routing
    location / {
      try_files $uri $uri/ /index.html;
    }

    # location /api/ {
    #     proxy_pass https://api-eligibility.univers.ci/api;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     add_header Access-Control-Allow-Origin *;
    #     add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
    #     add_header Access-Control-Allow-Headers "Authorization,Content-Type";

    #     if ($request_method = 'OPTIONS') {
    #         return 204;
    #     }
    # }
  }
}



